import { AdapterEmitter, type AvatarAdapter, type AdapterEvent, type AdapterListener, makeSdkError } from './adapter';
import { SDK_ERROR_CODES, type LifecycleState, type TranscriptEntry } from './types';

// Simulates the Socket SDK conversation loop so the demo runs end-to-end
// without live credentials, and so error logging can be exercised on demand.

const GREETING = "Hi! I'm the mock avatar. The real Kaltura SDK is not connected yet — everything you see here (events, transcript, errors) flows through the same adapter and logging pipeline the live SDK will use.";

const REPLIES = [
  'Got it. In live mode this reply would be generated by your avatar flow and spoken over WebRTC.',
  'This transcript entry came through the same `transcript-entry` event the real Socket SDK emits.',
  'Try the "Simulate error" buttons to see how typed SDK errors land in the event console and the logger.',
];

export class MockAdapter implements AvatarAdapter {
  readonly mode = 'mock' as const;
  private emitter = new AdapterEmitter();
  private state: LifecycleState = 'uninitialized';
  private sessionId: string | null = null;
  private transcript: TranscriptEntry[] = [];
  private micMuted = false;
  private replyIndex = 0;
  private timers: number[] = [];
  private container: HTMLElement | null = null;

  async connect(container: HTMLElement): Promise<void> {
    this.container = container;
    this.setState('connecting');
    await this.delay(600);
    this.sessionId = `mock-${Math.random().toString(36).slice(2, 10)}`;
    this.setState('connected');
    await this.delay(500);
    this.renderPlaceholder();
    this.emitter.emit('video-ready', { element: this.container.firstElementChild });
    this.emitter.emit('mic-granted', { stream: null });
    this.setState('ready');
    this.emitter.emit('ready', { sessionId: this.sessionId });
    this.schedule(() => this.speak(GREETING), 800);
    this.setState('in-conversation');
  }

  disconnect(): void {
    this.timers.forEach(clearTimeout);
    this.timers = [];
    this.setState('ended');
    this.emitter.emit('disconnected', { reason: 'client disconnect' });
  }

  destroy(): void {
    this.disconnect();
    this.emitter.clear();
    if (this.container) this.container.innerHTML = '';
  }

  sendText(text: string): void {
    if (this.state !== 'in-conversation') {
      this.emitError(3001, 'sendText() called while not in conversation');
      return;
    }
    this.emitter.emit('user-speech', { text, isFinal: true });
    this.addTranscript('User', text);
    const reply = REPLIES[this.replyIndex % REPLIES.length];
    this.replyIndex += 1;
    this.schedule(() => this.speak(reply), 900);
  }

  injectDPP(data: object | string): void {
    if (typeof data === 'string') {
      try {
        JSON.parse(data);
      } catch {
        this.emitError(5003, 'Invalid DPP JSON');
        return;
      }
    }
    this.emitter.emit('raw', { event: 'dpp-injected', payload: data });
  }

  muteMic(): void {
    this.micMuted = true;
  }

  unmuteMic(): void {
    this.micMuted = false;
  }

  isMicMuted(): boolean {
    return this.micMuted;
  }

  getState(): LifecycleState {
    return this.state;
  }

  getSessionId(): string | null {
    return this.sessionId;
  }

  getTranscript(): TranscriptEntry[] {
    return [...this.transcript];
  }

  on(event: AdapterEvent, listener: AdapterListener): () => void {
    return this.emitter.on(event, listener);
  }

  // Demo-only hook: raise a documented SDK error code on demand.
  simulateError(code: number): void {
    const spec = SDK_ERROR_CODES[code];
    this.emitError(code, spec ? `Simulated ${spec.name}` : `Simulated unknown error ${code}`);
    if (spec?.recoverable) {
      this.setState('reconnecting');
      this.emitter.emit('reconnecting', { attempt: 1 });
      this.schedule(() => {
        this.setState('in-conversation');
        this.emitter.emit('reconnected', {});
      }, 1500);
    }
  }

  private emitError(code: number, message: string): void {
    const spec = SDK_ERROR_CODES[code];
    this.emitter.emit('error', makeSdkError(code, message, spec?.recoverable ?? false));
  }

  private speak(text: string): void {
    this.emitter.emit('avatar-speaking-start', undefined);
    this.emitter.emit('avatar-speech', { text });
    this.addTranscript('Avatar', text);
    this.schedule(() => this.emitter.emit('avatar-speaking-end', undefined), Math.min(4000, 40 * text.length));
  }

  private addTranscript(role: 'Avatar' | 'User', text: string): void {
    const entry: TranscriptEntry = { role, text, timestamp: Date.now() };
    this.transcript.push(entry);
    this.emitter.emit('transcript-entry', entry);
  }

  private setState(next: LifecycleState): void {
    const from = this.state;
    this.state = next;
    this.emitter.emit('state-change', { from, to: next });
  }

  private renderPlaceholder(): void {
    if (!this.container) return;
    this.container.innerHTML =
      '<div class="mock-video"><div class="mock-face">🙂</div><div class="mock-caption">Mock avatar stream</div></div>';
  }

  private schedule(fn: () => void, ms: number): void {
    this.timers.push(window.setTimeout(fn, ms));
  }

  private delay(ms: number): Promise<void> {
    return new Promise((r) => this.timers.push(window.setTimeout(r, ms)));
  }
}
